# Generated by Django 5.0.6 on 2024-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('urgent_important', 'Acil ve Önemli'), ('not_urgent_important', 'Acil Değil ama Önemli'), ('urgent_not_important', 'Acil ama Önemsiz'), ('not_urgent_not_important', 'Acil Değil ve Önemsiz')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
